name: CookieClickerZ
version: '${project.version}'
main: com.zetaplugins.cookieclickerz.CookieClickerZ
api-version: '1.20'
softdepend:
  - PlaceholderAPI
  - DecentHolograms
  - FancyHolograms
authors: [Kartoffelchipss]
description: A highly customizable Cookie Clicker plugin!
website: zetaplugins.com

commands:
  cookieclicker:
    aliases:
      - cookieclickerz
      - cc
    description: Main command
  ccdebug:
    description: Generates debug logs
    permission: cookieclickerz.admin.debug

permissions:
  cookieclickerz.openmenu:
    default: true
    description: Permission to open the main menu
  cookieclickerz.useclicker:
    default: true
    description: Permission to use a clicker
  cookieclickerz.viewachievements:
    default: true
    description: Permission to view achievements
  cookieclickerz.upgrades:
    default: true
    description: Permission to open the upgrade shop
  cookieclickerz.buyupgrade.*:
    default: op
    description: Permission to buy all upgrades
  cookieclickerz.prestige:
    default: true
    description: Permission to open the prestige menu
  cookieclickerz.top:
    default: true
    description: Permission to open the top players menu
  cookieclickerz.numcheatsheet:
    default: true
    description: Permission to use the number shorthand cheatsheet
  cookieclickerz.admin.debug:
    default: op
    description: Permission to generate debug logs
  cookieclickerz.admin.reload:
    default: op
    description: Permission to reload the plugin
  cookieclickerz.admin.manageclickers:
    default: op
    description: Permission to add a clicker blocks
  cookieclickerz.admin.managecookies:
    default: op
    description: Permission to manage cookies
  cookieclickerz.admin.manageprestige:
    default: op
    description: Permission to manage cookies
  cookieclickerz.admin.manageevents:
    default: op
    description: Permission to manage events
  cookieclickerz.admin.manageachievements:
    default: op
    description: Permission to manage achievements
  cookieclickerz.admin.giveupgrade:
    default: op
    description: Permission to give upgrades